name: Pipeline API Banque DevOps et DevSecOps

on:
  push:
    branches: [ "main" ]

jobs:
  audit-securite-devsecops:
    name: Phase 1 Audits de Securite DevSecOps
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code source
        uses: actions/checkout@v4

      # CORRECTION DE L'URL OFFICIELLE TRUFFLEHOG
      - name: Scanner les fuites de secrets TruffleHog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          base: ""
          head: "HEAD"

      - name: Initialiser l analyse de code CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'java'

      - name: Build de verification
        run: mvn clean package -DskipTests

      - name: Effectuer l analyse CodeQL
        uses: github/codeql-action/analyze@v3

  build-and-test-devops:
    name: Phase 2 Compilation et Integration DevOps
    needs: audit-securite-devsecops
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code source
        uses: actions/checkout@v4

      - name: Configuration du JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilation avec Maven moderne
        run: mvn clean package -DskipTests

  auto-deploy-render:
    name: Phase 3 Deploiement Continu CD
    needs: build-and-test-devops
    runs-on: ubuntu-latest
    steps:
      - name: Declencher le deploiement sur Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"